Feat/landing onboarding 랜딩, 온보딩 구현
TeamYouniverse/Youniverse-Web-Release pull request #17
Opened 2022-04-03 17:26 UTC by Daeun-Danna-Lee

## ✅ PR check list

- [x] PR 제목: [feat/fix/refactor...] 작업 내용 한 줄 요약 (브랜치 이름) #이슈번호
- [ ] commit message가 적절한지 확인해주세요.
- [ ] 적절한 branch로 요청했는지 확인해주세요.
- [ ] Assignees, Label을 붙여주세요.
- [ ] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer로 등록해주세요.
- [ ] PR이 승인된 경우 해당 브랜치는 삭제 부탁드립니다.

<br/>

## 📝 PR 요약

- 랜딩부터 온보딩까지 모든 플로우를 작업했습니다.
- `/landing`, `/onboarding`, `/start`

<br/>

## 📌 변경 사항 및 주의 사항

- underlinedButton에서 {...props}로 버튼의 기본 프롭스를 모두 상속받고 있어서 직접 정의해줬던 handleClick은 삭제했습니다. 원래 버튼 쓰시던 거처럼 onClick={}으로 사용해주시면 됩니다.

<br/>

## 📸 ScreenShot
뷰가 많으니 직접 풀 받아서 보슈 (`/landing`)

2022-04-05 17:55 UTC, euijinkk requested changes
다은이 잘한다. 앱잼때보다 더 잘하는듯 굿굿,, 넘 고생많았따
초반이라 코멘트 많이 남길게!
컨벤션 맞출 것, 웹 에서 쓰이는 다양한 것들..., 코드 개선 등 다양하게 남겼습니다.

@Nahee-Park  나희도 봐주세요!

1. landing 1500 너무 짧은 것 같아요. 글자가 애니메이션 없이 바뀌어서 파악하기도 어렵네요. 디자이너와 상의해봐야할듯
2. onboarding -> start 가 3000ms 인데, 좀 긴거같아요. 1500~2000이 저는 좋네요. 이것도 디자이너와 상의

2022-04-05 17:55 UTC, euijinkk commented on pages/start.tsx
> +    }, 2900);
애니메이션은 3000인데 이거 2900으로 한게 번쩍이는 현상 해결하려고 한거지?
맞다면

```
animation-fill-mode: forwards 
```

를 추가해주면 해결될거같아. forwards는 애니메이션의 최종 상태 그대로 유지한다는 의미!
즉, bottom: -300px 그대로 유지되기 때문에, 번쩍이는 현상이 해결될거임.

2022-04-05 17:55 UTC, euijinkk commented on pages/start.tsx
> +            animation-duration: 3s;
3000을 
constant.ts로 분리해서, 애니메이션과 setTimeout에 함께 사용해서 재사용성을 높이면 유지/보수가 편할것같아요!

2022-04-05 17:55 UTC, euijinkk commented on pages/start.tsx
> +  const [isStartClicked, setIsStartClicked] = useState<boolean>(false);
원시타입은 타입 추론되기 때문에 boolean 선언해줄 필요 없어용!~

2022-04-05 17:55 UTC, euijinkk commented on pages/start.tsx
> +  const handleStartClicked = (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
e 사용하지 않네요! 지웁시다!

2022-04-05 17:55 UTC, euijinkk commented on pages/start.tsx
> +  const handleStartClicked = (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
@Nahee-Park 
handler 네이밍 컨벤션 정하면 좋을거같은데. 
나희는 onEventHandler 형식으로 쓰는 것을 선호하는 것 같고.

난 뭐든 상관없어~
나희 어떻게 생각해

2022-04-05 17:55 UTC, euijinkk commented on pages/start.tsx
> +    z-index: 10;
z-index 왜 준건가요?

2022-04-05 17:55 UTC, euijinkk commented on pages/start.tsx
> +    z-index: 10;
세로 크기 반응형으로 시도한거 좋은거같아염. 난 세로 반응형 고려 안한것 같은데, 내꺼 좀 수정해야겠군..

2022-04-05 17:55 UTC, euijinkk commented on pages/start.tsx
> +
지금 <시작> 텍스트와 <행성>의 위치가 애매한거같아. 사이즈에 따라 다른 그림이 나올수도 있을듯.
행성은 bottom: -150px로 표현하는 것이 맞겠고.
ButtonWrapper는 어떻게 해볼까나... 얘는 항상 행성과 같이 바닥에 있어야 하잖아. 그래서 얘도 
position: fixed 줘서 바닥으로 부터 픽셀로 표현하면 될거같아!

밑 사진은 다른 기기 사이즈일때 행성과 시작버튼이 일치하지 않는 예시
<img width="301" alt="image" src="https://user-images.githubusercontent.com/24906022/161804857-bc1cc75c-8ced-41d9-85ed-f5701e0e07d7.png">

2022-04-05 17:55 UTC, euijinkk commented on pages/start.tsx
> +    z-index: 10;
여기 z-index는 행성보다 위에 위치시키기 위해 필요한건가요? 
기본 z-index가 1이니까 하나씩 높여서 표현하면 좋을거같아요

2022-04-05 17:55 UTC, euijinkk commented on pages/start.tsx
> +};
visibility는 따로 줄 필요가 없을것 같아요.

```suggestion
    ${(props) =>
      props.isStartClicked
        && css`
            animation-duration: 3s;
            animation-name: ${planetAnimation};
          `}
  `,
};
```

2022-04-05 17:55 UTC, euijinkk commented on pages/start.tsx
> +    width: 70vw;
70vw는 어떤 의미죠?

width를 안주어도 동일하게 동작하네요!

2022-04-05 17:55 UTC, euijinkk commented on pages/start.tsx
> +    justify-content: center;
얘도 필요없는것같아요!

Main에서 이미 중앙정렬 해두어서, PlanerWrapper가 Image를 fit하게 감싸는 형태로 표현되면,
중앙정렬 해줄 필요가 없겠죵?

2022-04-05 17:55 UTC, euijinkk commented on pages/landing.tsx
> +          <Image src={planetImage} alt="planet image" />
alt는 이미지를 설명하는 부분이기 때문에, 
image / photo 와 같은 단어를 넣는 것은 무의미해요!
다른 lint 에서는 에러를 띄우기도 한답니다~

빼줘도 좋겠습니다!

2022-04-05 17:55 UTC, euijinkk commented on pages/start.tsx
> +          `
```suggestion
            animation-duration: 3s;
            animation-name: ${planetAnimation};
            animation-fill-mode: forwards;
          `
```

2022-04-05 17:55 UTC, euijinkk commented on pages/landing.tsx
> +          <Image src={planetImage} alt="planet image" />
그리고 지금 PlanetWrapper에 `width: 243px`을 주었는데, image에 주는 것이 더 직관적이지 않을까요?

```suggestion
          <Image width="243px" src={planetImage} alt="planet image" />
```

2022-04-05 17:55 UTC, euijinkk commented on pages/landing.tsx
> +    width: 243px;
☺️

2022-04-05 17:55 UTC, euijinkk commented on pages/landing.tsx
> +    justify-content: center;
필요없을거같습니당

2022-04-05 17:55 UTC, euijinkk commented on pages/landing.tsx
> +          <p>{message}</p>
messageIndex만 받아서 표현하는 것이 더 유연하고 확장성이 좋은 것같아용~
그리고 1500 같은 매직 넘버는 상수로 뺴면 유지보수가 쉬울것같아여

```suggestion
  const [messageIndex, setMessageIndex] = useState(0);

  useEffect(() => {
    let timer = setInterval(() => {
      setMessageIndex(messageIndex + 1);
      if (messages.length === messageIndex) {
        router.push('/onboarding');
      }
    }, 1500);
    return () => clearTimeout(timer);
  }, []);

  return (
    <>
      <Header />
      <Styled.Main>
        <Styled.TextWrapper>
          <IntroduceSentence />
          <p>{messages[messageIndex]}</p>
```

2022-04-05 17:55 UTC, euijinkk commented on pages/landing.tsx
> +    z-index: 10;
☺️ z-index 꼭 필요한지 확인해주세요!

필요없는 tag 및 스타일은 렌더링 속도를 저하시키기 때문에, 최소화하는 것이 좋아서 코멘트 남깁니다~!

2022-04-05 17:55 UTC, euijinkk commented on src/components/Onboarding/PageIndicator.tsx
> +  index: Number;
type은 소문자~

```suggestion
  index: number;
```

2022-04-05 17:55 UTC, euijinkk commented on src/components/Onboarding/OnboardingCarousel.tsx
> +  };
이렇게만 해도 정상 동작하는 것 같은데, 혹시 didScroll과 afterChange는 왜 필요할까요?

```suggestion
  const handleBeforeChange = (beforeSlide) => {
    updateSlideIndex(beforeSlide + 1);
  };

```

2022-04-05 17:55 UTC, euijinkk commented on src/components/Onboarding/PageIndicator.tsx
> +    if (index < 2) {
2 숫자가 조금 거슬리는데요! ㅋㅋ
pages 데이터를 onboarding 컴포넌트에서 받아와서 하위컴포넌트들 (OnboardingCarousel, PageIndicator)에 뿌려주는 구조로 바꾸고, 

`index < pages.length` 로 바꾸는 것은 어떨까요

2022-04-05 17:55 UTC, euijinkk commented on src/components/Onboarding/PageIndicator.tsx
> +      nextArrow.click();
지금 `updateSlideIndex`를 Carousel에 내려줘서 beforeChange로 주고 있는데요. PageIndicator에 내려주고, 이 함수에서 실행시켜주는 것이 자연스러운 것 같아요. 더불어, prev 도 구현한다고 했을 때, 확장성도 좋은것 같습니다. (prev 필요하지 않을까요? ㅋㅋ 없으니까 어색하네요.

```suggestion
      let nextArrow = document.getElementsByClassName('slick-next')[0] as HTMLElement;
      nextArrow.click();
      updateSlideIndex(idx => idx+1)
```

idx => idx +1 이것은 useState에서 이전 상태값을 받아와서 + 1 해주는 문법입니다. index를 내려줄 필요는 없겠어요!

2022-04-05 17:55 UTC, euijinkk commented on src/components/Onboarding/PageIndicator.tsx
> +    e.preventDefault();
preventDefault 필요할까요?
이는 보통 submit event일때 쓰입니다. submit는 자동으로 페이지를 새로고침하는 기능이 있어 이를 막고자 사용합니다.

2022-04-05 17:55 UTC, euijinkk commented on src/components/Onboarding/PageIndicator.tsx
> +      <Styled.SkipButton onClick={handleSkipClick}>건너뛰기</Styled.SkipButton>
사소한 것인데, button의 기본 type은 submit입니당. submit는 input의 값을 제출하는데 쓰이는 것으로 여기서는 적절하지 않ㄴ네요~ 이런것은 type="button" 으로 바꿔주면 좋겠습니댜~!

```suggestion
      <Styled.SkipButton type="button" onClick={handleSkipClick}>건너뛰기</Styled.SkipButton>
```

2022-04-05 17:55 UTC, euijinkk commented on src/components/Onboarding/PageIndicator.tsx
> +  `,
```suggestion
  FirstStar: styled.div<{ index: number }>`
    ${(props) => (props.index == 0 ? { opacity: 1 } : { opacity: 0.6 })}
  `,
  SecondStar: styled.div<{ index: number }>`
    ${(props) => (props.index == 1 ? { opacity: 1 } : { opacity: 0.6 })}
  `,
  ThirdStar: styled.div<{ index: number }>`
    ${(props) => (props.index == 2 ? { opacity: 1 } : { opacity: 0.6 })}
  `,
```

2022-04-05 17:55 UTC, euijinkk commented on src/components/Onboarding/PageIndicator.tsx
> +  `,
\* -  selector 개인적으로 조금 위험한것 같음!
안에 있는 모든것에 대해서 적용하는 것이니까,
1. 불필요하게 적용될 수 있다.
2. 확장성이 부족하다. 다른것들이 추가되었을 때 대응하기 어렵다.

그래서 하나하나 지정해주는 것이 좋아보임!
그리고 여기서는 Image에 대해서만 크기를 지정해주면 되니까 Image 태그 안에서 width 와 height를 지정해주자!

각각의 star에 props를 내려주고 있는데, 상위 엘리먼트에 index를 내려주고, nth-of-type을 이용하여 동적으로 할당하면 되겠습니다!

FirstStar, SecondStar 얘들 스타일드 컴포넌트 안쓰고 걍 div로 해줘도 될듯

```suggestion
  PageStarWrapper: styled.div<{ index: number }>`
    display: flex;
    justify-content: space-between;
    width: 20vw;
    max-width: 150px;
    height: 33px;

    & > div {
      opacity: 0.6;
    }

    & > div:nth-of-type(${({ index }) => index + 1}) {
      opacity: 1;
    }
```

2022-04-05 19:56 UTC, Nahee-Park reviewed
진짜 너무 고생했습미다.. 아니 웹개발 안했다면서 실력이 엄청 느셨네요 ㄷ ㄷ !!!!!!!!!! 
너무 빨리 끝내버려서 심심하다면 캐로셀 넘어갈 때 그 인덱스가 라우팅에도 반영되도록 하는 것도 한 번 구현해보면 좋을 것 같기도 합미다 ㅋ ㅋ 그치만 이건 완전 선택사항이라 한 귀로 흘리셔도 좋아여 ㅎㅎ 
여튼 고생하셨습니다 !

2022-04-05 19:56 UTC, Nahee-Park commented on pages/landing.tsx
> +  `,
Main 부분은 main테그 쓰는 게 더 좋을 것 같아요!
그리고 저 부분 반복적으로 자주 나오는 스타일이라 lib/style/mixin.ts에 `flexColumnCenter`로 으진이가 정의해뒀는데 가져다 써도 좋을 것 같아요 
```suggestion
  Main: styled.main`
    ${flexColumnCenter}
  `,
```

2022-04-05 19:56 UTC, Nahee-Park commented on pages/start.tsx
> +  const handleStartClicked = (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
@euijinkk  나도 크게 상관 없습니다 ! 흠 뭘로 할까요 ?

2022-04-05 19:56 UTC, Nahee-Park commented on pages/landing.tsx
> +    align-items: center;
이 부분도 ! 
```suggestion
    ${flexColumnCenter}
    justify-content: space-between;
```

2022-04-05 19:56 UTC, Nahee-Park commented on pages/onboarding.tsx
> +  const [currSlide, setCurrSlide] = useState<number>(0);
이 부분도 원시타입이라 타입추론될 것 같아요 ! 따로 타입 지정해주지 않아도 될 것 같아요

2022-04-05 19:56 UTC, Nahee-Park commented on pages/start.tsx
> +    align-items: center;
```suggestion
    ${flexColumnCenter}
    justify-content: space-between;
```

2022-04-05 19:56 UTC, Nahee-Park commented on pages/start.tsx
> +  `,
```suggestion
  Main: styled.main`
    ${flexColumnCenter}
  `,
```

2022-04-05 19:56 UTC, Nahee-Park commented on pages/start.tsx
> +
오 이렇게 한다면 ButtonWrapper 테그에서는 그냥 z-index만 한번에 조정해주고 (행성 위로 올라가도록), 
```javascript
          <UnderlinedButton onClick={handleStartClicked}>시작</UnderlinedButton>
          <RoundButton
            handleClick={() => {
              router.push('login');
            }}
          >
            이미 우주가 있다면
          </RoundButton>
```
이 부분  버튼 각각 스타일 조정하는 편이 좋을 것 같아요 !

근데 개인적인 생각으로는 시작 버튼이 꼭 행성 위꼭대기에 붙어 있어야할까 ..? 싶은 생각이 들긴 해요
그냥 이대로 놔둬도 크게 이질감 드는 비율이 없어서 굳이 수정하지 않아도 될 것 같기도 하고 ..

2022-04-05 19:56 UTC, Nahee-Park commented on pages/start.tsx
> +    z-index: 10;
<img width="600" alt="image" src="https://user-images.githubusercontent.com/81923229/161835409-2fb7f897-d803-4ced-9f28-ba0abcb41af7.png">
뭔가 이런 케이스에서 행성이 글자를 덮칠까봐 올린 것 같아여 ! 
근데 z-index:1 로만 해도 똑같은 효과를 낼 수 있어서 숫자는 조금 낮춰도 될 것 같긴 해요 !

2022-04-05 19:56 UTC, Nahee-Park commented on src/components/common/UnderlinedButton.tsx
> +  return <Styled.Root {...props}>{children}</Styled.Root>;
이 부분 이렇게 수정한 거 좋은데 기본적으로 html button element의 타입들을 확장시켜서 interface 타입을 지정하는 것이 더 안전할 것 같아요 ! 
+) 클래스 이름도 추가할 수 있도록 가능성을 열어두면 좋을 것 같아요 ! 스타일링 할 때 좀 더 자유로울 수 있도록 ! 
```javascript
interface ButtonProps extends HTMLAttributes<HTMLButtonElement>{
  className?: string;
  children: string;
  [key: string]: any;
}
```

2022-04-05 19:56 UTC, Nahee-Park commented on src/components/common/UnderlinedButton.tsx
> +  return <Styled.Root {...props}>{children}</Styled.Root>;
이렇게 하면 버튼테그에 들어갈 수 있는 요소들에 대한 타입이 ButtonProps interface에 들어간다는 장점이 있습니다!

2022-04-06 06:23 UTC, Nahee-Park commented
> 진짜 너무 고생했습미다.. 아니 웹개발 안했다면서 실력이 엄청 느셨네요 ㄷ ㄷ !!!!!!!!!! 너무 빨리 끝내버려서 심심하다면 캐로셀 넘어갈 때 그 인덱스가 라우팅에도 반영되도록 하는 것도 한 번 구현해보면 좋을 것 같기도 합미다 ㅋ ㅋ 그치만 이건 완전 선택사항이라 한 귀로 흘리셔도 좋아여 ㅎㅎ 여튼 고생하셨습니다 !

@euijinkk 
이거 밑의 두 의견 둘 다 동의.. 
landing 1500 너무 짧은 것 같아요. 글자가 애니메이션 없이 바뀌어서 파악하기도 어렵네요. 디자이너와 상의해봐야할듯
onboarding -> start 가 3000ms 인데, 좀 긴거같아요. 1500~2000이 저는 좋네요. 이것도 디자이너와 상의

2022-04-06 09:15 UTC, dannaward commented on pages/landing.tsx
> +          <p>{message}</p>
@euijinkk 이가 써준 코드 보면 계속 messageIndex가 0이 찍히고 온보딩으로 라우팅이 안돼 이유가 뭘까?
```tsx
useEffect(() => {
  let timer = setInterval(() => {
    setMessageIndex(messageIndex + 1);
    console.log(messageIndex);
    if (messages.length === messageIndex) {
      router.push('/onboarding');
    }
  }, 1500);
  return () => clearTimeout(timer);
}, []);
```
<img width="334" alt="image" src="https://user-images.githubusercontent.com/71601985/161941186-f60b60fe-dd06-4426-94f3-895afdb7646d.png">

2022-04-06 09:21 UTC, dannaward commented on pages/landing.tsx
> +          <p>{message}</p>
```tsx
useEffect(() => {
    let timer = setInterval(() => {
      if (messages.length - 1 === messageIndex) {
        router.push('/onboarding');
      } else {
        setMessageIndex(messageIndex + 1);
      }
    }, 1500);
    return () => clearTimeout(timer);
  }, [messageIndex]);
```

일단 이렇게 해결은 했다만 저게 왜 안됐었는지 모르겠다 ,,

2022-04-06 09:28 UTC, dannaward commented on pages/landing.tsx
> +          <Image src={planetImage} alt="planet image" />
398f6e7742e59a4c7420f9b8106cab32b1f182f9

2022-04-06 09:31 UTC, dannaward commented on pages/landing.tsx
> +  `,
5fb3975a826011ccd7b181dd8eda7563a7ab9059

2022-04-06 09:32 UTC, dannaward commented on pages/landing.tsx
> +    align-items: center;
70de2b8589f139600e6135208a320bfb761c98e3

2022-04-06 09:36 UTC, dannaward commented on pages/landing.tsx
> +    z-index: 10;
![image](https://user-images.githubusercontent.com/71601985/161945381-2026d3e4-5ba7-4a8d-a047-86637ff2ccbc.png)
이런 상황을 막고 싶었슴다 배경의 일부인 행성이 감히 텍스트를 가리는 상황!
근데 10은 너무 높다고 생각해서 1으로 내렸습니당 ㅎㅎ 9170dd8f323e6a4652bf4c9e1bb2bfb7ab0783f5

2022-04-07 03:42 UTC, dannaward commented on pages/landing.tsx
> +    justify-content: center;
25b82f5d7a9cb850a1d6ab4ba454858576e5d6cd

2022-04-07 03:46 UTC, dannaward commented on pages/onboarding.tsx
> +  const [currSlide, setCurrSlide] = useState<number>(0);
스위프트에서는 타입이 추론되는 원시타입들도 
1. 코드에 명시적으로 타입을 나타내기 위해 (사람을 위해)
2. 컴파일 단계에서 불필요한 타입 추론 단계를 줄이기 위해 (컴퓨터를 위해)
항상 타입을 명시할 것을 권장하고 있는데, 리액트나 자스에서는 어떤 이유로 권장되지 않나요?

2022-04-07 03:50 UTC, dannaward commented on pages/onboarding.tsx
> +  const [currSlide, setCurrSlide] = useState<number>(0);
db095b9d2f7db3c5257f940d542f5694c325639e

2022-04-07 03:51 UTC, dannaward commented on pages/start.tsx
> +  const [isStartClicked, setIsStartClicked] = useState<boolean>(false);
cc774c4b71a110afe7761b1c7a29b571205b6907

2022-04-07 03:53 UTC, dannaward commented on pages/start.tsx
> +  const handleStartClicked = (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
8838e7de1ed177813077daef9120b9494bc3eb2d 일단 e부터 삭제~

2022-04-07 03:54 UTC, dannaward commented on pages/start.tsx
> +    }, 2900);
기므진 천재
5c8036961c12b17a9a98c8ed26766e597365544d

2022-04-07 03:56 UTC, dannaward commented on pages/start.tsx
> +  `,
4eb1880d3f8a562500b2e8c83cbc80ebf82434d0

2022-04-07 03:58 UTC, dannaward commented on pages/start.tsx
> +    align-items: center;
19c65cce6c246a4148a0157d836d9415f6cce090

2022-04-07 08:06 UTC, euijinkk commented on pages/start.tsx
> +  const handleStartClicked = (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
나는 이벤트랑 이벤트 핸들러 함수랑 잘 구분됐으면 젛겠음!!


onClick 이벤트에는
ClickHandler 또는
HandleClick 으로

그런데 ClickHandler는 앞에 명사가 붙는 경우가 많아서 한눈에 안 보이는 것 같아.
ButtonClickHandler 라든지..

그래서 나는 Handle 로 시작하는 것이 핸들러랑 이벤트랑 명확하게 구분해주지 않을까 싶어!!

@Nahee-Park @dannaward

2022-04-07 08:09 UTC, euijinkk commented on pages/onboarding.tsx
> +  const [currSlide, setCurrSlide] = useState<number>(0);
오!! 이건 생각 안해봣당. 스위프트에서는 모두 명시하구나.

일단 타스에서는 팀에 따라 모든 타입을 명시하기도 한다고 하던데,추론해주는 것은 명시하지않는 것이 일반적인 것 같아.

스위프트랑은 어떤 차이가 있길래 컨벤션에서 차이가날까...

2022-04-07 08:16 UTC, euijinkk commented on pages/start.tsx
> +
bottom, height랑 margin
3개를 주고 있는데, 바닥에 붙인다고 생각하면
bottom만 주면 돼서 더 효율적일거같아요!

디자인적으로도 일관성 있고, css도 적게 쓰는 것 같은데, 혹시 이대로 남겼을때 다른 이점이 있을까용?

2022-04-07 08:16 UTC, euijinkk commented on src/components/common/UnderlinedButton.tsx
> +  return <Styled.Root {...props}>{children}</Styled.Root>;
우왕 너 천재당

2022-04-07 08:18 UTC, euijinkk commented on pages/landing.tsx
> +          <p>{message}</p>
앗 ㅋㅋ length는 1부어 시작하고
index는 0부터 시작해서 그런듯.

-1 해줘서 해결 잘됐네용!~

2022-04-07 08:19 UTC, euijinkk commented on pages/landing.tsx
> +    z-index: 10;
짱짱맨!

2022-04-09 06:10 UTC, Nahee-Park commented on pages/start.tsx
> +  const handleStartClicked = (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
@euijinkk  좋아 !

2022-04-09 08:21 UTC, Nahee-Park commented on pages/landing.tsx
> +          <p>{message}</p>
@dannaward 저런 방식으로 해결했다면 setInterval보다 setTimeout이 더 적절한 것 같아요! 
```typescript
  useEffect(() => {
    setTimeout(() => {
      console.log(messageIndex);
      if (messages.length - 1 === messageIndex) {
        router.push('/onboarding');
      } else {
        setMessageIndex(messageIndex + 1);
      }
    }, 1500);
  }, [messageIndex]);
```
이렇게요! 
setInterval되고, clear되는 과정이 불필요하게 반복되고 있는데 동작이 결국 setTimeout과 동일할 것 같습니다

2022-04-09 08:24 UTC, Nahee-Park commented on pages/landing.tsx
> +          <p>{message}</p>
추가적으로, 의진이가 말해준 방법이 안된 이유는 훅의 클로저 문제인 것 같아요. state값이 useEffect의 스코프 안에 갇혀있어서 업데이트가 안되는 것 같습니다. 이 부분을 해결하기 위해 사용할 수 있는 커스텀 훅이 있는데 이거 제가 자세하게 정리해서 포스팅할 예정이니 일단은 위와 같은 방식으로 넘어가도 좋을 것 같아요! 넘 고생했슴다 : D

2022-05-03 12:12 UTC, soleu commented
와 코드리뷰 미쳤네

2025-08-11 00:55 UTC, closed without merging